In [3]:
import numpy as np
import math as mt
import pandas as pd

# Básicos

In [2]:
z=np.zeros(10)

In [3]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [27]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#matriz identidade função: np.eye(0,0)
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
Z = np.random.random((3,3))
Z

array([[0.88002527, 0.09400023, 0.97082023],
       [0.70190923, 0.27956909, 0.84443183],
       [0.75815038, 0.44088829, 0.53727261]])

In [41]:
Z = np.random.random((3,3,3))
Z

array([[[0.54385269, 0.48178236, 0.9410318 ],
        [0.89198084, 0.27040296, 0.29155419],
        [0.10058269, 0.44015991, 0.06591309]],

       [[0.20699812, 0.25178021, 0.5055123 ],
        [0.29047756, 0.23092602, 0.77243379],
        [0.25593473, 0.75264023, 0.24900216]],

       [[0.46991172, 0.48712524, 0.77549455],
        [0.38366849, 0.98449142, 0.57911235],
        [0.02760281, 0.50220161, 0.94612041]]])

In [45]:
Z = np.random.random((3,3))
Z

array([[0.39478898, 0.39486008, 0.18995971],
       [0.10141476, 0.05497649, 0.48138085],
       [0.04020506, 0.7021839 , 0.02171922]])

In [47]:
Zmin, Zmax = Z.min(), Z.max()

In [49]:
Zmin

#elemento mínimo da matriz

0.02171921544866351

In [50]:
Zmax

#máximo da matriz

0.702183904868263

In [53]:
Z.mean()

#média da matriz

0.26460989346835234

In [61]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [67]:
np.tile(np.array([[1,2],[2,2]]),(2,2))

array([[1, 2, 1, 2],
       [2, 2, 2, 2],
       [1, 2, 1, 2],
       [2, 2, 2, 2]])

In [79]:
Z = np.random.random((5,5))
Z

array([[0.19414388, 0.47806911, 0.43196056, 0.82573882, 0.43644421],
       [0.68191674, 0.75921567, 0.88836388, 0.94598859, 0.42715893],
       [0.0733566 , 0.36742005, 0.63428101, 0.5053179 , 0.84302404],
       [0.42309296, 0.45738498, 0.00310098, 0.1622289 , 0.20266747],
       [0.11103649, 0.44146141, 0.39233901, 0.70902606, 0.10483008]])

# Multiplicação de Matrizes:

In [71]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [76]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [264]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Matrizes

In [97]:
z=np.array([[1,2,7],[4,6,1],[5,4,3]])
z

array([[1, 2, 7],
       [4, 6, 1],
       [5, 4, 3]])

In [101]:
y=np.array([[10,20,30],[50,60,70],[30,40,80]])
y

array([[10, 20, 30],
       [50, 60, 70],
       [30, 40, 80]])

In [104]:
z+y

array([[11, 22, 37],
       [54, 66, 71],
       [35, 44, 83]])

In [108]:
y.shape!=z.shape

False

In [112]:
x=np.array([[10,80,40],[50,60,70]])

# Soma Matrizes

In [119]:
def somamatrizes(a,b):
    if a.shape!=b.shape:
        print('Impossível de ser calculado!')
    else:
        print(a+b)
    
    

In [120]:
somamatrizes(y,z)

[[11 22 37]
 [54 66 71]
 [35 44 83]]


In [121]:
somamatrizes (y,x)

Impossível de ser calculado!


# Troca de Linhas e Colunas

In [137]:
def trocalinhas(mat,l1,l2):
    #troca as linhas l1 e l2 da matriz mat de posição
    for i in range (mat.shape[1]):
        aux=mat[l1,i]
        mat[l1,i]=mat[l2,i]
        mat[l2,i]=aux
    return mat

In [140]:
x

array([[10, 80, 40],
       [50, 60, 70]])

In [146]:
x.shape[1]
#colunas

3

In [147]:
x.shape[0]
#linhas

2

In [150]:
trocalinhas(x,1,0)

array([[50, 60, 70],
       [10, 80, 40]])

In [161]:
def trocacolunas(mat,l1,l2):
    #troca as colunas l1 e l2 da matriz mat de posição
    for i in range (mat.shape[0]):
        aux=mat[i,l1]
        mat[i,l1]=mat[i,l2]
        mat[i,l2]=aux
    return mat

In [163]:
x

array([[70, 60, 50],
       [40, 80, 10]])

In [165]:
trocacolunas(x,0,2)

array([[50, 70, 60],
       [10, 40, 80]])

# Matriz Randômica

In [201]:
p=np.random.randint(25, size=(2, 4))
p

array([[ 6, 14, 20, 14],
       [20,  3, 23, 21]])

# Normalizando uma matriz

In [202]:
np.mean(p)
#Média

15.125

In [203]:
np.std(p)
#Desvio Padrão

6.863626956646173

In [204]:
ç=p-np.mean(p)
ç

array([[ -9.125,  -1.125,   4.875,  -1.125],
       [  4.875, -12.125,   7.875,   5.875]])

In [209]:
ç/np.std(p)

array([[-1.32947202, -0.16390751,  0.71026587, -0.16390751],
       [ 0.71026587, -1.76655871,  1.14735257,  0.85596144]])

In [210]:
ç//np.std(p)

array([[-2., -1.,  0., -1.],
       [ 0., -2.,  1.,  0.]])

In [211]:
ç = (p - np.mean (p)) / (np.std (p))
print(ç)

[[-1.32947202 -0.16390751  0.71026587 -0.16390751]
 [ 0.71026587 -1.76655871  1.14735257  0.85596144]]


# Multiplicação de Matrizes sem a função do Nunpy

In [217]:
v=np.array([[1,2,3],[4,5,6]])
v

array([[1, 2, 3],
       [4, 5, 6]])

In [222]:
k=np.array([[4,6,3],[6,4,3],[4,1,3]])
k

array([[4, 6, 3],
       [6, 4, 3],
       [4, 1, 3]])

In [227]:
t=np.array([[1,2,3,4],[1,4,5,3],[1,5,6,3],[1,2,3,6]])
t

array([[1, 2, 3, 4],
       [1, 4, 5, 3],
       [1, 5, 6, 3],
       [1, 2, 3, 6]])

In [261]:
def matmult(a,b):
    #multiplica as matrizes a e b "na marra", sem usar a função de multiplicação de matrizes do NumPy
    nan='ERROR'
    nlina=a.shape[0]
    ncola=a.shape[1]
    nlinb=b.shape[0]
    ncolb=b.shape[1]
    if ncola!=nlinb:
        print("Dimensões incompatíveis")
        return nan
    nlinc=nlina
    ncolc=ncolb
    c=np.zeros((nlinc,ncolc))
    for i in range (nlinc):
        for j in range (ncolc):
            c[i,j]=0
            for k in range (ncola):
                c[i,j]=c[i,j]+a[i,k]*b[k,j]
    return c

In [262]:
matmult(v,k)

array([[28., 17., 18.],
       [70., 50., 45.]])

In [263]:
matmult(v,t)

Dimensões incompatíveis


'ERROR'

# Calcular o determinante de uma matriz usando o método de escalonamento.

In [269]:
def det(a):
    #calcula o determinante da matriz pelo método do escalonamento
    nlins=a.shape[0]
    ncols=a.shape[1]
    mult=1
    for linbase in range(nlins):
        #pega o elemento da diagonal como fator da linha base
        fator=a[linbase,linbase]
        mult=mult*fator
        #divide os elementos da linha base pelo fator, pra ficar com 1 na diagonal
        for col in range(ncols):
            a[linbase,col]=a[linbase,col]/fator
        #substitui os elementos das linhas abaixo de forma a fazer os elementos abaixo do fator ficarem com zero
        for lin in range (linbase+1,nlins):
            #pega como "pivô" o elemento da linha que está na coluna do fator da linha base 
            pivo=a[lin,linbase]
            for col in range(ncols):
                a[lin,col]=a[lin,col]-pivo*a[linbase,col]
        #print (mat)
    return mult

# Exercicio 2 A2

In [16]:
def primo(n):
    divisores=2
    for i in range (2,n):
        if n%i==0:
            divisores=divisores+1
    return divisores
def primos(n):
    primos=[]
    for x in range (1,n+1):
        if primo(x)==2:
            primos.append(x)
    return primos

In [271]:
def q2fatores(n):
    p=primos(n)
    divisores=[]
    for i in range(1,len(p)):
        while n%p[i]==0:
            divisores.append(p[i])
            n=n/p[i]
    divunicos=np.unique(divisores)
    m=np.zeros((len(divunicos),2))
    m=np.asmatrix(m)
    for a in range (0,len(divunicos)):
        m[a,0]=divunicos[a]
    for e in range (0,len(divunicos)):
        m[e,1]=divisores.count(divunicos[e])
    return m

In [272]:
q2fatores(45)

matrix([[3., 2.],
        [5., 1.]])

# DIAS NUNPY

In [274]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

# CÁLCULOS NUNPY

In [275]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

# FORMANDO INTEIROS EM MATRIZES

In [304]:
Z = np.random.uniform(5,10,10)
Z

array([5.0642264 , 6.78172897, 7.664684  , 8.53674442, 7.55838611,
       8.83759397, 7.22965528, 8.82603574, 5.14145421, 5.6848409 ])

In [305]:
print (Z - Z%1)

[5. 6. 7. 8. 7. 8. 7. 8. 5. 5.]


In [ ]:
print (np.floor(Z))

# SORT (Bubble Sort)

In [318]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.15317737 0.18624044 0.29858935 0.36341593 0.42345915 0.65954953
 0.66705159 0.69140822 0.75278458 0.92301857]


###### BUBBLE SORT SEM USAR A FUNÇÃO

In [1]:
def bubble(lista):
    for i in range (0,len(lista)-1):
        x=lista[i]
        y=lista[i+1]
        if x>y:
            lista[i+1]=x
            lista[i]=y
    for i in range (0,len(lista)-1):
        x=lista[i]
        y=lista[i+1]
        if x>y:
            bubble(lista)
    return lista

In [3]:
bubble([1,5,10,2,8,4,3,20])

[1, 2, 3, 4, 5, 8, 10, 20]

In [329]:
len([1,5,10,2,8,4,3,20])

8

In [330]:
def meu_bobo_sort(lista):
    houvetroca=1
    passadas=0 #serve para controlar o loop e evitar que vá até o final da lista desnecessariamente
    while houvetroca==1:
        houvetroca=0
        for i in range(len(lista)-1-passadas):
            if lista[i]>lista[i+1]:
                aux=lista[i+1]
                lista[i+1]=lista[i]
                lista[i]=aux
                houvetroca=1
        passadas=passadas+1
    return lista

In [331]:
meu_bobo_sort([1,5,10,2,8,4,3,20])

[1, 2, 3, 4, 5, 8, 10, 20]

# COORDENADA CARTESIANA PARA POLAR


In [323]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)
print(Z)

[0.66109801 1.0197359  0.89331406 0.50954331 0.51785288 1.19650589
 0.45652921 0.73967919 0.87887044 0.87197052]
[0.36821694 0.27879036 0.46301955 0.1797357  0.91839863 0.73252161
 0.53563046 0.43372127 1.06708353 0.12163931]
[[0.61678504 0.23796385]
 [0.9803629  0.28062409]
 [0.79925514 0.39900029]
 [0.50133506 0.09109082]
 [0.31438509 0.41150167]
 [0.8895907  0.80015919]
 [0.39259094 0.23300489]
 [0.67119094 0.31085049]
 [0.42421364 0.76971166]
 [0.86552758 0.10580453]]


# CALCULANDO A TRANSPOSTA

In [13]:
x=np.array([[10,80,40],[50,60,70],[30,60,10]])
x

array([[10, 80, 40],
       [50, 60, 70],
       [30, 60, 10]])

In [6]:
def transposeMatrix(M):
    aux=[]
    for j in range(len(M[0])):
        linha=[]
        for i in range(len(M)):
            linha.append(M[i][j])
            aux.append(linha)
    return aux

In [14]:
transposeMatrix(x)

[[10, 50, 30],
 [10, 50, 30],
 [10, 50, 30],
 [80, 60, 60],
 [80, 60, 60],
 [80, 60, 60],
 [40, 70, 10],
 [40, 70, 10],
 [40, 70, 10]]

In [38]:
y=np.array([[1,4,5],[4,6,2],[2,0,5]])
y

array([[1, 4, 5],
       [4, 6, 2],
       [2, 0, 5]])

In [30]:
def matriznula(nlinhas,ncols):
    M=[]
    for i in range(nlinhas):
        linha=[0]*ncols
        M.append(linha)
    return M
        

In [43]:
def transposta(M):
    nlinhas=M.shape[0]
    ncolunas=M.shape[1]
    T=matriznula(ncolunas,nlinhas)
    for i in range(nlinhas):
        for j in range(ncolunas):
            T[j][i]=M[i][j]
    return np.array([T])

In [45]:
transposta(y)

array([[[1, 4, 2],
        [4, 6, 0],
        [5, 2, 5]]])